USE [master]
GO

/****** Object:  Database [Sjovik]    Script Date: 06/29/2011 21:13:37 ******/
CREATE DATABASE [Sjovik] ON  PRIMARY 
( NAME = N'ASPNETDB_3e2b6f0cd62d457cab652ecec19d9c7f_DAT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\aspnetdb.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5120KB )
 LOG ON 
( NAME = N'ASPNETDB_TMP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\aspnetdb_log.ldf' , SIZE = 504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [Sjovik] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sjovik].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Sjovik] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Sjovik] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Sjovik] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Sjovik] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Sjovik] SET ARITHABORT OFF 
GO

ALTER DATABASE [Sjovik] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Sjovik] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Sjovik] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Sjovik] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Sjovik] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Sjovik] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Sjovik] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Sjovik] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Sjovik] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Sjovik] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Sjovik] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Sjovik] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Sjovik] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Sjovik] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Sjovik] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Sjovik] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Sjovik] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Sjovik] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Sjovik] SET  READ_WRITE 
GO

ALTER DATABASE [Sjovik] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Sjovik] SET  MULTI_USER 
GO

ALTER DATABASE [Sjovik] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Sjovik] SET DB_CHAINING OFF 
GO

